---
services:
  db:
    image: jagadishkumpati/mypy:dbimage
    deploy:
      replicas: 1
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  auth_service:
    image: jagadishkumpati/mypy:authimage
    deploy:
      replicas: 1
    ports:
      - "5001:5001"
    networks:
      - mynetwork
    depends_on:
      - db
    

  book_service:
    image: jagadishkumpati/mypy:bookimage
    deploy:
      replicas: 1
    ports:
      - "5002:5002"
    networks:
      - mynetwork
    depends_on:
      - db
  borrow_service:
    image: jagadishkumpati/mypy:borrowimage
    deploy:
      replicas: 1
    ports:
      - "5003:5003"
    networks:
      - mynetwork
    depends_on:
      - db

  frontend:
    image: jagadishkumpati/mypy:appimage
    deploy:
      replicas: 1
    ports:
      - "5000:5000"
    networks:
      - mynetwork
    depends_on:
      - auth
      - book
      - borrow

networks:
  mynetwork:
    driver: overlay
